remotes:
  denon_x4700h:
    display_name: Denon Receiver
    commands:
    - name: Power Toggle
      protocol: DENON
      data: "0x2A4C028A0088"
      nbits: 48
      repeats: 0
    - name: Volume Up
      protocol: DENON
      data: "0x2A4C0280E86A"
      nbits: 48
      repeats: 0      
    - name: Volume Down
      protocol: DENON
      data: "0x2A4C0288E862"
      nbits: 48
      repeats: 0      
  sony_bravia:
    display_name: Sony Bravia
    commands:
    - name: Power
      protocol: SIRC
      data: '0xA90'
      nbits: 12
    - name: Input
      protocol: SIRC
      data: '0xA50'
      nbits: 12
    - name: Home
      protocol: SIRC
      data: '0x070'
      nbits: 12
    - name: Apps
      protocol: SIRC
      data: '0x2A23'
      nbits: 15
    - name: Tv
      protocol: SIRC
      data: '0x250'
      nbits: 12
    - name: Left
      protocol: SIRC
      data: '0x2D0'
      nbits: 12
    - name: Right
      protocol: SIRC
      data: '0xCD0'
      nbits: 12
    - name: Up
      protocol: SIRC
      data: '0x2F0'
      nbits: 12
    - name: Down
      protocol: SIRC
      data: '0xAF0'
      nbits: 12
    - name: Enter
      protocol: SIRC
      data: '0xA70'
      nbits: 12
    - name: Back
      protocol: SIRC
      data: '0x62E9'
      nbits: 15
    - name: Mute
      protocol: SIRC
      data: '0x290'
      nbits: 12
    - name: Vol_up
      protocol: SIRC
      data: '0x490'
      nbits: 12
    - name: Vol_dn
      protocol: SIRC
      data: '0xC90'
      nbits: 12
    - name: Ch_next
      protocol: SIRC
      data: '0x090'
      nbits: 12
    - name: Ch_prev
      protocol: SIRC
      data: '0x890'
      nbits: 12
    - name: Play
      protocol: SIRC
      data: '0x2CE9'
      nbits: 15
    - name: Pause
      protocol: SIRC
      data: '0x4CE9'
      nbits: 15
    - name: Stop
      protocol: SIRC
      data: '0x0CE9'
      nbits: 15
    - name: Fwd
      protocol: SIRC
      data: '0x1CE9'
      nbits: 15
    - name: Rew
      protocol: SIRC
      data: '0x6CE9'
      nbits: 15
    - name: Prev
      protocol: SIRC
      data: '0x1EE9'
      nbits: 15
    - name: Next
      protocol: SIRC
      data: '0x5EE9'
      nbits: 15
    - name: Rec
      protocol: SIRC
      data: '0x02E9'
      nbits: 15
    - name: Netflix
      protocol: SIRC
      data: '0x1F58'
      nbits: 15
    - name: Google_play
      protocol: SIRC
      data: '0x3123'
      nbits: 15
    - name: Red
      protocol: SIRC
      data: '0x52E9'
      nbits: 15
    - name: Green
      protocol: SIRC
      data: '0x32E9'
      nbits: 15
    - name: Yellow
      protocol: SIRC
      data: '0x72E9'
      nbits: 15
    - name: Blue
      protocol: SIRC
      data: '0x12E9'
      nbits: 15
    - name: Action_menu
      protocol: SIRC
      data: '0x6923'
      nbits: 15
    - name: Guide
      protocol: SIRC
      data: '0x6D25'
      nbits: 15
    - name: Help
      protocol: SIRC
      data: '0x5923'
      nbits: 15
    - name: Title_list
      protocol: SIRC
      data: '0x5358'
      nbits: 15
    - name: Audio
      protocol: SIRC
      data: '0xE90'
      nbits: 12
    - name: Screen___
      protocol: SIRC
      data: '0x0AE9'
      nbits: 15
    - name: Swap
      protocol: SIRC
      data: '0xDD0'
      nbits: 12
    - name: Dig_analo
      protocol: SIRC
      data: '0x58EE'
      nbits: 15
    - name: Tv_radio
      protocol: SIRC
      data: '0x7558'
      nbits: 15
    - name: Exit
      protocol: SIRC
      data: '0xC70'
      nbits: 12
    - name: Ext_box_menu
      protocol: SIRC
      data: '0x4923'
      nbits: 15
    - name: '1'
      protocol: SIRC
      data: '0x010'
      nbits: 12
    - name: '2'
      protocol: SIRC
      data: '0x810'
      nbits: 12
    - name: '3'
      protocol: SIRC
      data: '0x410'
      nbits: 12
    - name: '4'
      protocol: SIRC
      data: '0xC10'
      nbits: 12
    - name: '5'
      protocol: SIRC
      data: '0x210'
      nbits: 12
    - name: '6'
      protocol: SIRC
      data: '0xA10'
      nbits: 12
    - name: '7'
      protocol: SIRC
      data: '0x610'
      nbits: 12
    - name: '8'
      protocol: SIRC
      data: '0xE10'
      nbits: 12
    - name: '9'
      protocol: SIRC
      data: '0x110'
      nbits: 12
    - name: '0'
      protocol: SIRC
      data: '0x910'
      nbits: 12
    - name: I_plus
      protocol: SIRC
      data: '0x5D0'
      nbits: 12
    - name: Txt
      protocol: SIRC
      data: '0xFD0'
      nbits: 12

